# Generated by Django 2.1.1 on 2018-09-25 12:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='api/Group/', verbose_name='Иконка')),
                ('description', models.TextField(max_length=512, verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Группы',
                'verbose_name': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Group')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('checked', models.BooleanField(null=True, verbose_name='Заполнен модератором')),
            ],
            options={
                'verbose_name_plural': 'Элементы',
                'verbose_name': 'Элемент',
            },
            bases=('api.group',),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group', verbose_name='Родитель'),
        ),
    ]
