# Generated by Django 2.1.1 on 2018-09-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='inheritElement',
            field=models.IntegerField(default=0, verbose_name='Дочерних Элементов'),
        ),
        migrations.AddField(
            model_name='group',
            name='inheritGroup',
            field=models.IntegerField(default=0, verbose_name='Дочерних Групп'),
        ),
    ]
