# Generated by Django 2.1.1 on 2018-09-25 22:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180925_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.FileField(upload_to=api.models.make_upload_path, verbose_name='Иконка'),
        ),
    ]
