# Generated by Django 2.1.1 on 2018-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180925_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(upload_to='api/Group/', verbose_name='Иконка'),
        ),
    ]
